In [17]:
!pip uninstall tensorflow

^C


In [3]:
import sys; print(sys.executable)

c:\Users\user\miniconda3\envs\tf_py3.10\python.exe


In [1]:
import tensorflow as tf
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [4]:
tf.nn.relu

<function tensorflow.python.ops.gen_nn_ops.relu(features, name=None)>

In [3]:
tf.sqrt

<function tensorflow.python.ops.math_ops.sqrt(x, name=None)>

In [3]:
tf.sqrt(2.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.4142135>

In [4]:
tf.Variable(tf.zeros((1, 2, 3))).assign_sub

<bound method BaseResourceVariable.assign_sub of <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>>

In [7]:
tf.Variable.assign_sub

<function tensorflow.python.ops.variables.Variable.assign_sub(self, delta, use_locking=False, name=None, read_value=True)>

In [9]:
type(tf.Variable(True))

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [2]:
from dense_pcn_layer import DensePCNLayer
%load_ext autoreload
%autoreload 2
DensePCNLayer(5, 0.1).update_b()

In [14]:
tf.transpose(tf.constant([[1, 2, 34]]))

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [34]])>

In [16]:
int(tf.Variable(True))

1

In [149]:
A = DensePCNLayer(5, 0.1, 'relu')
A.state = tf.Variable(tf.random.normal((10, 5)))
B = DensePCNLayer(6, 0.1, 'relu')
A.next_layers=[B]
C = DensePCNLayer(7, 0.1, 'relu')
B.prev_layer = A
B.next_layers = [C]
C.prev_layer = B
print(A.state)

<tf.Variable 'Variable:0' shape=(10, 5) dtype=float32, numpy=
array([[ 0.8383709 ,  0.8744468 , -1.3766357 , -0.88216835,  0.7896468 ],
       [-0.2707406 , -0.4805285 , -0.8325282 , -0.48009422, -2.1997411 ],
       [ 1.997145  , -2.7608094 ,  0.05157735,  1.0802573 , -1.3829137 ],
       [-2.2060118 , -0.39752686,  1.3451974 ,  0.16647801, -0.9244042 ],
       [-0.51555187,  1.6435454 ,  0.8980932 ,  0.8847658 , -0.00363228],
       [ 0.02259825, -0.668252  , -0.22662018,  0.93124986,  2.4502451 ],
       [-0.21800673,  0.32034826, -0.45866057, -1.2506627 ,  0.07264269],
       [-0.48427993, -0.52621007,  0.85881436, -0.12489915, -0.7448117 ],
       [ 0.27844778, -0.83060706, -2.642085  , -0.34290436, -0.7415135 ],
       [-1.1402401 ,  0.3976387 ,  1.4665952 ,  2.4886267 , -0.46057713]],
      dtype=float32)>


In [150]:
b_out = B(A.state)

tf.Tensor(0.6324556, shape=(), dtype=float32)


In [151]:
c_out = C(b_out)

tf.Tensor(0.5773503, shape=(), dtype=float32)


In [133]:
B.update_state()

In [153]:
print(tf.math.reduce_std(B.state, axis=0))

tf.Tensor([0.514722   0.8293352  0.7881699  0.9222408  0.18895394 0.37207156], shape=(6,), dtype=float32)


In [165]:
B.update_state()
print(tf.math.reduce_std(B.state, axis=0))
B.update_wts()
print(tf.math.reduce_std(B.wts, axis=0))


tf.Tensor(
[7.1796869e+12 8.4603453e+12 6.1750908e+12 7.9279864e+12 2.6842998e+12
 5.7117513e+12], shape=(6,), dtype=float32)
tf.Tensor([inf inf inf inf inf inf], shape=(6,), dtype=float32)
