In [1]:
import sys; print(sys.executable)
import tensorflow as tf
from dense_pcn_layer import DensePCNLayer
%load_ext autoreload
%autoreload 2

c:\Users\user\miniconda3\envs\tf_py3.10\python.exe


In [2]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [48]:
A = DensePCNLayer(1000, 0.00001, 'relu')
A.state = tf.Variable(tf.random.normal((10, 1000)))
B = DensePCNLayer(2000, 0.00001, 'relu')
A.next_layers=[B]
C = DensePCNLayer(3000, 0.00001, 'relu')
B.prev_layer = A
B.next_layers = [C]
C.prev_layer = B
b_out = B(A.state)
c_out = C(b_out)

In [4]:
print(tf.math.reduce_std(B.state, axis=1))
print(tf.math.reduce_std(C.state, axis=1))

tf.Tensor(
[0.867127   0.85285854 0.82102525 0.7714853  0.84216297 0.8220902
 0.80572784 0.826424   0.8339445  0.82653   ], shape=(10,), dtype=float32)
tf.Tensor(
[0.8247157  0.8152491  0.8068497  0.7668341  0.82119274 0.83073676
 0.79787946 0.8286458  0.8357024  0.813989  ], shape=(10,), dtype=float32)


In [50]:
for i in range(10):
      B.update_state()
      B.update_wts()
      B.update_b()
      print(tf.reduce_sum((B.predict_next() - B(A.predict_next()))**2)
            +tf.reduce_sum((C.predict_next() - C(B.predict_next()))**2)
            +tf.reduce_sum((A.predict_next()-B.predict_prev())**2)
            +tf.reduce_sum((B.predict_next()-C.predict_prev())**2))

tf.Tensor(111906.22, shape=(), dtype=float32)
tf.Tensor(111464.734, shape=(), dtype=float32)
tf.Tensor(111050.98, shape=(), dtype=float32)
tf.Tensor(110663.234, shape=(), dtype=float32)
tf.Tensor(110299.89, shape=(), dtype=float32)
tf.Tensor(109959.39, shape=(), dtype=float32)
tf.Tensor(109640.34, shape=(), dtype=float32)
tf.Tensor(109341.44, shape=(), dtype=float32)
tf.Tensor(109061.4, shape=(), dtype=float32)
tf.Tensor(108799.06, shape=(), dtype=float32)


In [44]:
from conv_pcn_layer import Conv2DPCNLayer
A = Conv2DPCNLayer(1, (3, 3), 0.0000001, 'relu')
A.state = tf.Variable(tf.random.normal((10, 100, 100, 1)))
B = Conv2DPCNLayer(5, (3, 3), 0.0000001, 'relu')
A.next_layers=[B]
C = Conv2DPCNLayer(9, (3, 3), 0.0000001, 'relu')
B.prev_layer = A
B.next_layers = [C]
C.prev_layer = B
b_out = B(A.state)
c_out = C(b_out)

In [45]:
for i in range(10):
    B.update_state()
    B.update_wts()
    B.update_b()
    print(tf.reduce_sum((B.predict_next() - B(A.predict_next()))**2)
        +tf.reduce_sum((C.predict_next() - C(B.predict_next()))**2)
        +tf.reduce_sum((A.predict_next()-B.predict_prev())**2)
        +tf.reduce_sum((B.predict_next()-C.predict_prev())**2))

tf.Tensor(2469259.0, shape=(), dtype=float32)
tf.Tensor(2404970.0, shape=(), dtype=float32)
tf.Tensor(2347657.0, shape=(), dtype=float32)
tf.Tensor(2296605.0, shape=(), dtype=float32)
tf.Tensor(2251175.0, shape=(), dtype=float32)
tf.Tensor(2210795.0, shape=(), dtype=float32)
tf.Tensor(2174953.5, shape=(), dtype=float32)
tf.Tensor(2143191.5, shape=(), dtype=float32)
tf.Tensor(2115097.5, shape=(), dtype=float32)
tf.Tensor(2090304.1, shape=(), dtype=float32)


In [34]:
tf.nn.conv2d_transpose(tf.random.normal((5, 98, 98, 400)), tf.random.normal((3, 3, 20, 400), dtype='float'), strides=1, output_shape=(5, 100, 100, 20), padding="VALID")

<tf.Tensor: shape=(5, 100, 100, 20), dtype=float32, numpy=
array([[[[ 1.40237122e+01,  2.29071198e+01,  7.06505346e+00, ...,
          -1.03080893e+01, -2.04299889e+01, -2.37659245e+01],
         [ 2.53957024e+01,  3.50859451e+01, -5.90144634e+00, ...,
           2.83811722e+01, -2.24869614e+01,  3.77032042e+00],
         [ 7.78454437e+01,  5.08785553e+01, -4.75738144e+01, ...,
           1.99083023e+01, -1.86189480e+01,  6.32436981e+01],
         ...,
         [ 8.02130604e+00, -2.15839691e+01,  4.52961807e+01, ...,
          -2.97243652e+01,  3.46271400e+01,  4.92470589e+01],
         [ 4.69250183e+01, -2.21724205e+01, -5.21473541e+01, ...,
          -4.72643423e+00,  3.25484276e+01, -3.03961620e+01],
         [ 1.54510918e+01,  7.25128365e+00, -9.77683258e+00, ...,
          -3.74727287e+01,  2.47304802e+01,  2.80516376e+01]],

        [[ 1.43276825e+01,  3.48415375e-01,  2.31293755e+01, ...,
           3.85568848e+01,  6.85474014e+00,  1.58393612e+01],
         [-3.92274475e+01,  4

In [20]:
tf.raw_ops.Conv2DBackpropFilter(input=t2, filter_sizes=(3, 3, 6, 20), out_backprop=t1, strides=[1,1,1,1], padding="VALID")

InvalidArgumentError: {{function_node __wrapped__Conv2DBackpropFilter_device_/job:localhost/replica:0/task:0/device:GPU:0}} Conv2DBackpropFilter: Size of out_backprop doesn't match computed: actual = 100, computed = 96 spatial_dim: 1 input: 98 filter: 3 output: 100 stride: 1 dilation: 1 [Op:Conv2DBackpropFilter]

In [526]:
tf.reshape(tf.zeros((5, 3, 1)), (5, 3, 1))

<tf.Tensor: shape=(5, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
tf.nn.conv1d(tf.ones((5, 10))[:, :, None], tf.ones((3, 1, 15)), stride=1, padding='SAME')

<tf.Tensor: shape=(5, 10, 15), dtype=float32, numpy=
array([[[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.

In [15]:
tf.nn.conv1d_transpose(tf.zeros((5, 10))[:, :, None], tf.zeros((3, 15, 1)), padding='SAME', strides=1, output_shape=(5, 10, 15))

<tf.Tensor: shape=(5, 10, 15), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.

In [39]:
a = tf.Variable(tf.convert_to_tensor([-1.]*5))

In [40]:
print(tf.nn.relu(a))
print(a)

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([-1., -1., -1., -1., -1.], dtype=float32)>
