In [1]:
import sys; print(sys.executable)
import tensorflow as tf
from dense_pcn_layer import DensePCNLayer
%load_ext autoreload
%autoreload 2

c:\Users\user\miniconda3\envs\tf_py3.10\python.exe


In [ ]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
A = DensePCNLayer(1000, 0.0001, 'relu')
A.state = tf.Variable(tf.random.normal((10, 1000)))
B = DensePCNLayer(2000, 0.0001, 'relu')
A.next_layers=[B]
C = DensePCNLayer(3000, 0.0001, 'relu')
B.prev_layer = A
B.next_layers = [C]
C.prev_layer = B
b_out = B(A.state)
c_out = C(b_out)

In [451]:
print(tf.math.reduce_std(B.state, axis=1))
print(tf.math.reduce_std(C.state, axis=1))

tf.Tensor(
[0.84094095 0.7784857  0.83700114 0.80799556 0.8009426  0.80006677
 0.81136584 0.8144749  0.8911321  0.84035516], shape=(10,), dtype=float32)
tf.Tensor(
[0.8477947  0.7714897  0.85687315 0.7999754  0.80470955 0.7979575
 0.79655695 0.808746   0.8912567  0.8409304 ], shape=(10,), dtype=float32)


In [522]:
B.update_state()
B.update_wts()
B.update_b()
print(tf.reduce_sum((B.predict_next() - B(A.predict_next()))**2)
      +tf.reduce_sum((C.predict_next() - C(B.predict_next()))**2)
      +tf.reduce_sum((A.predict_next()-B.predict_prev())**2)
      +tf.reduce_sum((B.predict_next()-C.predict_prev())**2))

tf.Tensor(98948.08, shape=(), dtype=float32)


In [523]:
tf.zeros((5, 1, 3)) @ tf.zeros((5, 3, 1))

<tf.Tensor: shape=(5, 1, 1), dtype=float32, numpy=
array([[[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]]], dtype=float32)>

In [526]:
tf.reshape(tf.zeros((5, 3, 1)), (5, 3, 1))

<tf.Tensor: shape=(5, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

In [13]:
tf.nn.conv1d(tf.ones((5, 10))[:, :, None], tf.ones((3, 1, 15)), stride=1, padding='SAME')

<tf.Tensor: shape=(5, 10, 15), dtype=float32, numpy=
array([[[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3.

In [15]:
tf.nn.conv1d_transpose(tf.zeros((5, 10))[:, :, None], tf.zeros((3, 15, 1)), padding='SAME', strides=1, output_shape=(5, 10, 15))

<tf.Tensor: shape=(5, 10, 15), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.